name: C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build
      run: g++ -std=c++11 -o unit_tests *.cpp

    - name: Run tests
      run: ./unit_tests

