name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile C++ tests
      working-directory: './OOSE Project/OOSE Homework 5 Code'
      run: g++ -std=c++11 -o unit_tests test_financial_docs.cpp

    - name: Run unit tests
      working-directory: './OOSE Project/OOSE Homework 5 Code'
      run: ./unit_tests
